import './gmpObrasProposal.css';

const services = [
  { number: "01", title: "Sitio web y embudo de consultas", text: "Una presencia institucional diseñada para explicar, mostrar evidencia y ordenar el paso desde la búsqueda hasta la reunión.", items: ["Home y propuesta de valor", "Gustavo Pinto como referente técnico", "Obras, casos, preguntas frecuentes y testimonios", "Landing de consulta, formulario y WhatsApp", "Analytics, Search Console y medición de consultas"] },
  { number: "02", title: "Contenido orgánico", text: "Una presencia activa para que quien llegue por Google pueda validar la experiencia y el trabajo real de GMP Obras.", items: ["16 publicaciones mensuales", "4 reels o videos cortos mensuales", "8 historias de apoyo", "Facebook e Instagram", "Obras, procesos, decisiones técnicas y respuestas frecuentes"] },
  { number: "03", title: "Gestión de Google Ads", text: "Campañas de búsqueda para captar personas que ya evalúan construir, ampliar o solicitar un presupuesto.", items: ["Investigación de palabras clave", "Segmentación en Comodoro Rivadavia", "Rada Tilly, si la cobertura lo confirma", "Términos negativos y calidad de consultas", "Seguimiento e informe mensual"] },
];

const flowSteps = [
  ["01", "Búsqueda en Google", "Palabras relacionadas o keywords para encontrar una solución constructiva."],
  ["02", "Verificación", "La persona revisa las redes sociales y el sitio web de GMP Obras."],
  ["03", "Landing page", "Ingresa a la página sugerida por Google y conoce la propuesta con más detalle."],
  ["04", "Formulario de consulta", "Completa los datos iniciales de su proyecto para ordenar la consulta."],
  ["05", "WhatsApp o email", "El contacto se recibe y organiza por el canal elegido: WhatsApp o correo."],
  ["06", "Reunión y presupuesto", "Se coordina una reunión presencial o virtual y se prepara el presupuesto."],
];

const futureProducts = [
  ["01", "Blog, contenidos técnicos y posicionamiento orgánico", "Incorporación de un blog y generación de contenidos sobre construcción, obras y preguntas frecuentes para ampliar el alcance orgánico en Google."],
  ["02", "Chatbot de orientación en la web", "Un asistente inicial para que una persona pueda describir su proyecto y saber si tiene sentido avanzar con una consulta, sin reemplazar el criterio profesional."],
  ["03", "Agente de IA para WhatsApp", "Configuración de un asistente para responder preguntas frecuentes, ordenar datos iniciales y derivar cada conversación a atención humana cuando corresponda."],
  ["04", "Elaborador de presupuestos con ChatGPT", "Configuración de un proyecto en ChatGPT Work para organizar información, preparar cada proyecto y emitir presupuestos con un agente de OpenAI, sujeto a accesos y validaciones."],
  ["05", "Retargeting en Meta Ads", "Campañas para volver a mostrar casos, procesos y llamados a consulta a personas que ya visitaron el sitio o interactuaron con GMP Obras."],
  ["06", "Pauta en redes sociales", "Campañas de publicidad en Meta u otras redes sociales para ampliar el alcance de obras, servicios y contenidos, con inversión y modalidad a definir."],
];

export default function GmpObrasProposal() {
  return (
    <main className="gmp-landing">
      <header className="header">
        <img className="leandro" src="/propuestas/2026-09-gmp-obras-v01/logo-leandro.png" alt="Lic. Leandro Velasques" />
        <div className="prepared"><span>PRESUPUESTO PREPARADO PARA</span><img src="/propuestas/2026-09-gmp-obras-v01/gmp-obras.png" alt="GMP Obras" /></div>
      </header>

      <section className="hero">
        <div className="hero-copy"><p className="eyebrow">PROPUESTA DE SERVICIOS · CAPTACIÓN DIGITAL</p><h1>Que cada búsqueda con intención encuentre una forma clara de consultar.</h1><p>Una estrategia para GMP Obras: sitio, contenido orgánico y Google Ads orientados a personas que ya evalúan construir.</p><div className="facts"><span><b>03</b> soluciones integradas</span><span><b>Google</b> demanda activa</span><span><b>16</b> posteos mensuales</span></div></div>
        <img src="/propuestas/2026-09-gmp-obras-v01/obra-terminada.png" alt="Obra terminada de GMP Obras" />
      </section>

      <section className="intro section"><div><p className="eyebrow">01 / EL OBJETIVO</p></div><div><h2>Transformar interés concreto en consultas mejor calificadas.</h2><p>El sitio será el centro del recorrido. Google Ads atraerá búsquedas activas; las redes orgánicas aportarán evidencia, proceso y presencia. La primera etapa no contempla pauta en Meta ni LinkedIn.</p></div></section>

      <section className="services section" id="alcance"><div className="section-head"><div><p className="eyebrow">02 / EL ALCANCE</p><h2>Una base pensada para captar, explicar y ordenar.</h2></div><p>Tres soluciones coordinadas para que la presencia digital, la comunicación y la captación funcionen como un mismo sistema.</p></div><div className="service-grid">{services.map((service) => <article className="service-card" key={service.number}><div className="service-top"><span>{service.number}</span><small>SOLUCIÓN INTEGRADA</small></div><h3>{service.title}</h3><p>{service.text}</p><ul>{service.items.map((item) => <li key={item}>{item}</li>)}</ul></article>)}</div></section>

      <section className="funnel section"><div className="funnel-copy"><p className="eyebrow">03 / EL RECORRIDO</p><h2>Un recorrido que acompaña la decisión.</h2><p>La consulta se construye paso a paso: desde la búsqueda inicial hasta una conversación ordenada y un presupuesto con criterio técnico.</p></div><div className="flow">{flowSteps.map(([number, title, detail]) => <article key={number}><b>{number}</b><strong>{title}</strong><span>{detail}</span></article>)}</div></section>

      <section className="authority section"><div className="authority-photo"><img src="/propuestas/2026-09-gmp-obras-v01/obra-proceso-1.png" alt="Proceso constructivo de GMP Obras" /></div><div><p className="eyebrow">04 / AUTORIDAD Y EVIDENCIA</p><h2>Mostrar a GMP Obras desde el trabajo real.</h2><p>El rediseño prioriza obras, procesos, preguntas frecuentes, fotografías, videos y testimonios autorizados. Gustavo Pinto será presentado como Maestro Mayor de Obras y referente técnico de GMP Obras.</p><p>La forma de comunicar cualquier vínculo con Cassaforma se valida antes de publicarla.</p></div></section>

      <section className="team section"><div className="section-head team-intro"><div><p className="eyebrow">05 / EQUIPO RESPONSABLE</p><h2>Un equipo combinado de estrategia, implementación y comunicación.</h2></div><p>Leandro dirige el proyecto y coordina la implementación. Hola Agencia Digital acompaña la estrategia de contenidos y comunicación.</p></div><div className="team-grid"><article className="person-card leandro-card"><div className="person-brand"><div className="person-links"><a href="mailto:info@leandrovelasques.com.ar">info@leandrovelasques.com.ar</a><a href="https://www.leandrovelasques.com.ar">www.leandrovelasques.com.ar</a></div><img src="/propuestas/2026-09-gmp-obras-v01/triskel-leandro.png" alt="Símbolo de Leandro Velasques" /></div><div className="person-body"><img className="person-photo" src="/propuestas/2026-09-gmp-obras-v01/leandro-profile.jpg" alt="Lic. Leandro Velasques" /><div><span>DIRECTOR DEL PROYECTO</span><h3>Lic. Leandro Velasques</h3><p>Consultor y director de proyectos de IA aplicada a negocios, marketing digital y mejora de procesos.</p></div></div></article><article className="person-card hola-card"><div className="person-brand"><div className="person-links"><a href="https://www.instagram.com/holagenciadigital">@holagenciadigital</a><a href="https://www.holagenciadigital.com">www.holagenciadigital.com</a></div><img src="/propuestas/2026-09-gmp-obras-v01/hola-logo-clean.png" alt="Hola Agencia Digital" /></div><div className="person-body"><img className="person-photo" src="/propuestas/2026-09-gmp-obras-v01/daniela-rincon.jpg" alt="Daniela Rincón" /><div><span>CEO · HOLA AGENCIA | DIRECCIÓN GENERAL</span><h3>Daniela Rincón</h3><p>Dirección general de Hola Agencia Digital, docente de Marketing Digital en carreras de grado y posgrado de UADE y responsable del acompañamiento estratégico en contenidos y comunicación.</p></div></div></article></div></section>

      <section className="content section"><div className="section-head"><div><p className="eyebrow">06 / CONTENIDO ORGÁNICO</p><h2>Presencia constante para acompañar la decisión.</h2></div><p>Facebook e Instagram funcionan como evidencia visible de una empresa activa, con obras, conocimientos y personas detrás de cada proyecto.</p></div><div className="quantities"><div><b>16</b><span>publicaciones mensuales</span></div><div><b>04</b><span>reels o videos cortos</span></div><div><b>08</b><span>historias de apoyo</span></div></div></section>

      <section className="timeline section" id="cronograma"><div className="section-head"><div><p className="eyebrow">07 / DESPLIEGUE SUGERIDO</p><h2>Construir la base, activar la búsqueda y aprender.</h2></div><p>Las duraciones dependen del relevamiento, la aprobación de contenidos y la entrega de materiales por parte de GMP Obras.</p></div><div className="gantt" aria-label="Cronograma de despliegue"><div className="gantt-head"><span>Actividad</span><b>MES 01</b><b>MES 02</b><b>MES 03</b></div><div className="gantt-row meeting-row"><strong>Kick off · Reunión inicial y definición comercial</strong><i className="meeting-marker k0"><img src="/propuestas/2026-09-gmp-obras-v01/triskel-leandro.png" alt="Kick off" /></i></div><div className="gantt-row"><strong>Propuesta de plan de contenidos · Primeros 15 días</strong><i className="bar b1" /></div><div className="gantt-row"><strong>Arquitectura web básica · Home y landing para iniciar campañas</strong><i className="bar b2" /></div><div className="gantt-row meeting-row"><strong>Reunión de seguimiento</strong><i className="meeting-marker m1"><img src="/propuestas/2026-09-gmp-obras-v01/triskel-leandro.png" alt="Reunión de seguimiento" /></i></div><div className="gantt-row"><strong>Desarrollo web complementario · Servicios, Quiénes somos y ajustes web</strong><i className="bar b3" /></div><div className="gantt-row"><strong>Investigación y configuración de Google Ads · Días 15 a 30</strong><i className="bar b4" /></div><div className="gantt-row"><strong>Contenido orgánico · Plan editorial desde el día 15</strong><i className="bar b5" /></div><div className="gantt-row"><strong>Activación de Google Ads · Desde el mes 2</strong><i className="bar b6" /></div><div className="gantt-row"><strong>Seguimiento y optimización de campañas</strong><i className="bar b7" /></div><div className="gantt-row meeting-row"><strong>Reunión de seguimiento</strong><i className="meeting-marker m2"><img src="/propuestas/2026-09-gmp-obras-v01/triskel-leandro.png" alt="Reunión de seguimiento" /></i></div><div className="gantt-row meeting-row"><strong>Reunión de seguimiento</strong><i className="meeting-marker m3"><img src="/propuestas/2026-09-gmp-obras-v01/triskel-leandro.png" alt="Reunión de seguimiento" /></i></div></div></section>

      <section className="investment section"><div className="investment-lead"><p className="eyebrow">08 / INVERSIÓN</p><h2>Una inversión mensual global.</h2><p>El total reúne el trabajo y los costos definidos para esta etapa, con una única referencia económica mensual.</p><div className="investment-box"><span>HONORARIOS MENSUALES GLOBALES</span><strong>$700.000</strong><p>Incluye el sitio web, el contenido orgánico, la gestión de Google Ads, la pauta mensual de publicidad y los costos contemplados en esta propuesta.</p></div></div><div className="investment-standard"><div><span>INICIO PROPUESTO</span><b>Septiembre de 2026</b></div><div><span>FORMA DE PAGO</span><b>Transferencia bancaria, por adelantado, durante la primera semana de cada mes.</b></div><div><span>ACTUALIZACIÓN</span><b>Cada cuatro meses según la variación acumulada del Índice de Precios al Consumidor (IPC).</b></div><div><span>MODALIDAD FLEXIBLE</span><b>No se establece una permanencia mínima. El cliente puede solicitar la suspensión o finalización del servicio cuando lo considere necesario.</b></div><div><span>VIGENCIA</span><b>30 días desde la fecha de presentación.</b></div></div></section>

      <section className="third-party section"><div className="section-head"><div><p className="eyebrow">09 / COSTOS DE TERCEROS</p><h2>Costos contemplados y gastos variables.</h2></div><p>Se detalla qué se mantiene, qué no genera un cargo adicional y cuál es la sugerencia inicial para comenzar las campañas.</p></div><div className="third-party-grid"><article><span>DOMINIO ACTUAL</span><strong>gmp-obras.com</strong><p>Si se mantiene el dominio actual de GMP Obras, no se agrega un costo de registro.</p><b>Sin cargo adicional</b></article><article><span>CORREO Y HOSTING</span><strong>gpinto@gmpobras.com</strong><p>Se mantiene esta cuenta de correo si continúa abonada dentro del plan de hosting vigente, sin duplicar el costo.</p><b>Sin cargo adicional</b></article><article><span>PAUTA DE GOOGLE ADS</span><strong>$300.000 / mes</strong><p>Sugerencia inicial de inversión en medios para comenzar las campañas de búsqueda. Se considera dentro del total mensual global confirmado.</p><b>Inversión inicial sugerida</b></article></div></section>

      <section className="future-products section"><div className="section-head"><div><p className="eyebrow">10 / POSIBLES PRODUCTOS FUTUROS</p><h2>Otras soluciones para acompañar el crecimiento.</h2></div><p>Son líneas opcionales, a evaluar después de estabilizar el sitio, la generación de consultas y las necesidades operativas.</p></div><div className="future-products-grid">{futureProducts.map(([number, title, text]) => <article key={number}><b>{number}</b><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></section>

      <footer><img src="/propuestas/2026-09-gmp-obras-v01/logo-leandro.png" alt="Lic. Leandro Velasques" /><span>Propuesta preparada para GMP Obras · Agosto 2026</span></footer>
    </main>
  );
}

