import { useEffect, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { supabase } from '../../lib/supabase'

const CATEGORIES = { website: 'Sitio web', agenda: 'Agenda', crm: 'CRM', forms: 'Formularios', automation: 'Automatización', content: 'Contenido', design: 'Diseño', question: 'Consulta', other: 'Otro' }
const emptySub = () => ({ id: crypto.randomUUID(), title: '', description: '', expected_result: '' })
const empty = { client_id: '', title: '', description: '', affected_area: '', category: 'other', request_type: 'improvement', priority: 'normal', status: 'initiated', billing_status: 'pending', internal_note: '', client_note: '' }

export default function ChangeRequestCreate() {
  const navigate = useNavigate()
  const [clients, setClients] = useState([])
  const [form, setForm] = useState(empty)
  const [subRequests, setSubRequests] = useState([emptySub()])
  const [files, setFiles] = useState([])
  const [saving, setSaving] = useState(false)
  const [notice, setNotice] = useState(null)

  useEffect(() => { supabase.from('crm_clients').select('id, name, company').order('name').then(({ data }) => setClients(data || [])) }, [])
  const updateSub = (id, field, value) => setSubRequests(items => items.map(item => item.id === id ? { ...item, [field]: value } : item))
  const addFiles = (event) => {
    const selected = Array.from(event.target.files || [])
    const total = [...files, ...selected]
    const valid = total.filter(file => ['image/png', 'image/jpeg', 'image/webp', 'application/pdf'].includes(file.type) && file.size <= 10 * 1024 * 1024).slice(0, 8)
    if (valid.length !== total.length) setNotice({ type: 'error', text: 'Podés adjuntar hasta 8 imágenes o PDF de un máximo de 10 MB cada uno.' })
    setFiles(valid)
    event.target.value = ''
  }
  const save = async (event) => {
    event.preventDefault()
    if (!form.client_id || !form.title.trim() || !form.description.trim()) { setNotice({ type: 'error', text: 'Completá cliente, título y descripción general.' }); return }
    if (subRequests.some(item => !item.title.trim() || !item.description.trim())) { setNotice({ type: 'error', text: 'Completá el título y la descripción de cada sub-pedido.' }); return }
    setSaving(true)
    const attachments = await Promise.all(files.map(file => new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve({ name: file.name, type: file.type, size: file.size, url: reader.result }); reader.onerror = reject; reader.readAsDataURL(file) })))
    const { error } = await supabase.from('change_requests').insert({ ...form, origin: 'admin', attachments, sub_requests: subRequests.map((item, index) => ({ position: index + 1, ...item })) })
    if (error) setNotice({ type: 'error', text: `No se pudo guardar: ${error.message}` })
    else { navigate('/admin/pedidos-cambios', { state: { notice: 'Solicitud creada con sus sub-pedidos.' } }) }
    setSaving(false)
  }

  return <div className="max-w-5xl mx-auto pb-10">
    <div className="flex items-start justify-between gap-4 mb-8"><div><Link to="/admin/pedidos-cambios" className="text-xs font-bold text-[var(--color-deep-green)] hover:underline">← Volver a pedidos de cambios</Link><p className="text-xs font-bold uppercase tracking-[.16em] text-[var(--color-deep-green)]/55 mt-5">Carga interna</p><h1 className="text-3xl lg:text-4xl font-extrabold tracking-tight text-[var(--color-deep-green)]">Nueva solicitud</h1><p className="text-sm text-gray-500 mt-2 max-w-2xl">Registrá el tema general y separá los pedidos que necesitan resolverse con lógicas distintas.</p></div><div className="hidden sm:flex h-14 w-14 rounded-2xl bg-[var(--color-mint)]/45 items-center justify-center text-[var(--color-deep-green)]"><span className="material-symbols-outlined text-3xl">account_tree</span></div></div>
    {notice && <div className={`mb-5 rounded-xl px-4 py-3 text-sm font-semibold ${notice.type === 'error' ? 'bg-red-50 text-red-700 border border-red-100' : 'bg-emerald-50 text-emerald-800 border border-emerald-100'}`}>{notice.text}</div>}
    <form onSubmit={save} className="space-y-6">
      <section className="bg-white rounded-3xl border border-[var(--color-deep-green)]/10 shadow-sm p-6 md:p-8 space-y-5"><SectionTitle eyebrow="1 · Contexto común" title="¿Sobre qué tema es el pedido?" text="Esta información identifica la solicitud principal." /><div className="grid md:grid-cols-2 gap-5"><Field label="Cliente *"><select required value={form.client_id} onChange={e => setForm({ ...form, client_id: e.target.value })}><option value="">Seleccionar…</option>{clients.map(client => <option key={client.id} value={client.id}>{client.company || client.name}</option>)}</select></Field><Field label="Título general *"><input required value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} placeholder="Ej.: Mejorar la sección de charlas" /></Field></div><div className="grid md:grid-cols-2 gap-5"><Field label="Sitio, pantalla o sección"><input value={form.affected_area} onChange={e => setForm({ ...form, affected_area: e.target.value })} placeholder="Ej.: Charlas / observaciones" /></Field><Field label="Temática"><select value={form.category} onChange={e => setForm({ ...form, category: e.target.value })}>{Object.entries(CATEGORIES).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></Field></div><Field label="Descripción general *"><textarea required rows="8" value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} placeholder="Contá el contexto, el problema común y qué objetivo debería cumplir la mejora." /></Field></section>
      <section className="bg-white rounded-3xl border border-[var(--color-deep-green)]/10 shadow-sm p-6 md:p-8 space-y-5"><div className="flex flex-col sm:flex-row sm:items-start justify-between gap-4"><SectionTitle eyebrow="2 · Desglose" title="Sub-pedidos" text="Separá cada pedido cuando requiera una lógica, criterio o validación diferente." /><button type="button" onClick={() => setSubRequests(items => [...items, emptySub()])} className="shrink-0 rounded-xl bg-[var(--color-mint)]/40 px-3 py-2 text-xs font-extrabold text-[var(--color-deep-green)] hover:bg-[var(--color-mint)]"><span className="material-symbols-outlined text-sm align-middle">add</span> Agregar sub-pedido</button></div><div className="space-y-4">{subRequests.map((item, index) => <div key={item.id} className="rounded-2xl border border-[var(--color-deep-green)]/12 bg-[var(--color-refined-gray)]/55 p-5"><div className="flex items-center justify-between mb-4"><p className="text-sm font-extrabold text-[var(--color-deep-green)]">Sub-pedido {index + 1}</p>{subRequests.length > 1 && <button type="button" onClick={() => setSubRequests(items => items.filter(sub => sub.id !== item.id))} className="text-xs font-bold text-red-600 hover:underline">Quitar</button>}</div><div className="space-y-4"><Field label="Título del sub-pedido *"><input required value={item.title} onChange={e => updateSub(item.id, 'title', e.target.value)} placeholder="Ej.: Ver observaciones de clientes" /></Field><Field label="Descripción específica *"><textarea required rows="5" value={item.description} onChange={e => updateSub(item.id, 'description', e.target.value)} placeholder="Describí este pedido puntual y su comportamiento esperado." /></Field><Field label="Resultado esperado"><textarea rows="3" value={item.expected_result} onChange={e => updateSub(item.id, 'expected_result', e.target.value)} placeholder="Ej.: Mostrar comentarios dentro de la misma vista." /></Field></div></div>)}</div></section>
      <section className="bg-white rounded-3xl border border-[var(--color-deep-green)]/10 shadow-sm p-6 md:p-8 space-y-5"><SectionTitle eyebrow="3 · Material de referencia" title="Capturas y archivos" text="Adjuntá prints para que el pedido se pueda revisar con contexto." /><label className="flex min-h-32 cursor-pointer flex-col items-center justify-center rounded-2xl border-2 border-dashed border-[var(--color-deep-green)]/20 bg-[var(--color-refined-gray)]/50 px-5 text-center hover:border-[var(--color-deep-green)]/50"><span className="material-symbols-outlined text-3xl text-[var(--color-deep-green)]">upload_file</span><span className="mt-2 text-sm font-extrabold text-[var(--color-deep-green)]">Elegir capturas o archivos</span><span className="mt-1 text-xs text-gray-500">PNG, JPG, WEBP o PDF · hasta 8 archivos · 10 MB cada uno</span><input type="file" className="sr-only" accept="image/png,image/jpeg,image/webp,application/pdf" multiple onChange={addFiles} /></label>{files.length > 0 && <div className="grid sm:grid-cols-2 gap-2">{files.map((file, index) => <div key={`${file.name}-${index}`} className="flex items-center justify-between gap-3 rounded-xl bg-[var(--color-refined-gray)] px-3 py-2 text-sm"><span className="truncate font-semibold">{file.name}</span><button type="button" onClick={() => setFiles(items => items.filter((_, fileIndex) => fileIndex !== index))} className="shrink-0 text-xs font-bold text-red-600">Quitar</button></div>)}</div>}</section>
      <section className="bg-white rounded-3xl border border-[var(--color-deep-green)]/10 shadow-sm p-6 md:p-8 space-y-5"><SectionTitle eyebrow="4 · Seguimiento" title="Datos internos" text="Podés completar estos datos ahora o actualizarlos desde el listado." /><div className="grid md:grid-cols-3 gap-5"><Field label="Tipo de pedido"><select value={form.request_type} onChange={e => setForm({ ...form, request_type: e.target.value })}><option value="improvement">Mejora</option><option value="correction">Corrección</option><option value="new_feature">Nueva funcionalidad</option><option value="question">Consulta</option></select></Field><Field label="Prioridad"><select value={form.priority} onChange={e => setForm({ ...form, priority: e.target.value })}><option value="low">Baja</option><option value="normal">Normal</option><option value="high">Alta</option></select></Field><Field label="Facturación"><select value={form.billing_status} onChange={e => setForm({ ...form, billing_status: e.target.value })}><option value="pending">Pendiente de facturar</option><option value="included">Incluido en factura</option><option value="invoiced">Facturado</option><option value="not_billable">No facturable</option></select></Field></div><Field label="Nota interna"><textarea rows="4" value={form.internal_note} onChange={e => setForm({ ...form, internal_note: e.target.value })} placeholder="Contexto para preparar el trabajo técnico…" /></Field></section>
      <div className="flex flex-col-reverse sm:flex-row justify-end gap-3"><Link to="/admin/pedidos-cambios" className="rounded-xl px-5 py-3 text-center text-sm font-bold text-gray-500 hover:bg-gray-100">Cancelar</Link><button disabled={saving} className="btn-primary justify-center px-6 disabled:opacity-60">{saving ? 'Guardando…' : 'Crear solicitud'} <span className="material-symbols-outlined text-lg">check</span></button></div>
    </form>
  </div>
}

function SectionTitle({ eyebrow, title, text }) { return <div><p className="text-[10px] font-extrabold uppercase tracking-[.16em] text-[var(--color-deep-green)]/60">{eyebrow}</p><h2 className="mt-1 text-xl font-extrabold text-[var(--color-deep-green)]">{title}</h2><p className="mt-1 text-sm text-gray-500">{text}</p></div> }
function Field({ label, children }) { return <label className="block text-sm font-bold text-[var(--color-dark-gray)]">{label}<div className="mt-2 [&_input]:w-full [&_input]:rounded-xl [&_input]:border [&_input]:border-gray-200 [&_input]:bg-white [&_input]:px-4 [&_input]:py-3 [&_input]:text-sm [&_input]:outline-none [&_input:focus]:border-[var(--color-deep-green)] [&_select]:w-full [&_select]:rounded-xl [&_select]:border [&_select]:border-gray-200 [&_select]:bg-white [&_select]:px-4 [&_select]:py-3 [&_select]:text-sm [&_textarea]:w-full [&_textarea]:rounded-xl [&_textarea]:border [&_textarea]:border-gray-200 [&_textarea]:bg-white [&_textarea]:px-4 [&_textarea]:py-3 [&_textarea]:text-sm [&_textarea]:leading-relaxed [&_textarea]:outline-none [&_textarea:focus]:border-[var(--color-deep-green)]">{children}</div></label> }
